In [3]:
import numpy as np

In [4]:
ar1=np.array(6)

In [5]:
ar1

array(6)

In [6]:
ar2=np.array([3,5,6])

In [7]:
ar2

array([3, 5, 6])

In [8]:
ar3=np.array([2,5,6])

In [9]:
ar3

array([2, 5, 6])

In [10]:
zero_array=np.zeros((1,2))

In [11]:
zero_array

array([[0., 0.]])

In [12]:
ar4=np.arange(7,8,9)

In [13]:
ar4

array([7])

In [22]:
mat1=np.array([[1,2,3],[2,5,7],[4,5,6]])

In [23]:
print(mat1)

[[1 2 3]
 [2 5 7]
 [4 5 6]]


In [25]:
det_of_mat1=np.linalg.det(mat1)

In [26]:
det_of_mat1

-3.000000000000001

In [28]:
inverse=np.linalg.inv(mat1)

In [29]:
inverse

array([[ 1.66666667, -1.        ,  0.33333333],
       [-5.33333333,  2.        ,  0.33333333],
       [ 3.33333333, -1.        , -0.33333333]])

In [30]:
Dense=np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7],[0,0,1,1]])

In [32]:
Dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 0, 1, 1]])

In [33]:
from scipy.sparse import csr_matrix

In [34]:
sparse=csr_matrix(Dense)

In [35]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [36]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	5
  (2, 2)	6
  (2, 3)	7
  (3, 2)	1
  (3, 3)	1
